# example netlify.toml
[build]
  command = "next build"
  functions = "netlify/functions"
  publish = ".next"

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
